# Generated by Django 4.2.14 on 2025-10-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Petshop',
            fields=[
                ('id_petshop', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'petshop',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
                ('pshop_related', models.ForeignKey(blank=True, db_column='pshop_related', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.petshop')),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('comportamento', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('diferencial', models.CharField(blank=True, max_length=100, null=True)),
                ('id_dono', models.ForeignKey(blank=True, db_column='id_dono', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField()),
                ('id_petshop_agendamento', models.ForeignKey(blank=True, db_column='id_petshop_agendamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.petshop')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
