# Generated by Django 4.2.14 on 2025-10-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='petshop',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'managed': True},
        ),
    ]
