# Generated by Django 4.2.14 on 2025-10-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agendamento_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='duracao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
