# Generated by Django 4.2.14 on 2025-10-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicos_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshop',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='petshop',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
